import { z } from 'zod';
import { nullishString, nullishDateString, nullishNumber } from '../lib/zod';

export const OrganizationSchema = z.object({
    id: z.string(),
    name: z.string(),
    slug: z.string(),
    created_at: nullishDateString,
    updated_at: nullishDateString,
    member_count: nullishNumber,
    legal_name: nullishString,
    cnpj: nullishString,
    role: nullishString,
    subscription: z.object({
        id: z.string(),
        name: z.string(),
        plan_name: nullishString,
        is_active: z.boolean(),
        is_trial: z.boolean().nullish(),
        status: nullishString,
        dt_end: nullishDateString,
        expires_at: nullishDateString,
        created_at: nullishDateString,
        serpro_api_name: nullishString,
        serpro_api_is_trial: z.boolean().nullish(),
        serpro_cnpj: nullishString,
        serpro_cert_path: nullishString,
    }).nullish(),
    logradouro: nullishString,
    numero: nullishString,
    bairro: nullishString,
    municipio: nullishString,
    uf: nullishString,
    cep: nullishString,
    email: nullishString,
    telefone: nullishString,
    abertura: nullishString,
    situacao: nullishString,
    subscription_id: nullishString,
    cnpj_autor: nullishString,
    nome_fantasia: nullishString,
    cnae_principal: nullishString,
    regime_apuracao: nullishString,
    modalidade: nullishString,
    enquadramento: nullishString,
    data_enquadramento: nullishString,
    trial_ends_at: nullishDateString,
    subscription_status: nullishString,
    current_plan_id: nullishString,
    owner_email: nullishString,
    owner_name: nullishString
});

export type Organization = z.infer<typeof OrganizationSchema>;
